[project]
title = "Lakers Game Trends Dashboard"
version = "1.0.0"
port = 8501
slug = "lakers-game-trends"
entrypoint = "hello.py"

[branding]
name = "NBA Bets Dashboard"
logo = "images/lakers.png"
favicon = "images/favicon (1).ico"
primaryColor = "#552583"  # Lakers purple

[data.nba_vegas]
type = "csv"
path = "data/2018-2019_vegas.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(mes"
